/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CT417_Assigment1_Driver;

import java.util.ArrayList;

import org.checkerframework.checker.units.qual.m2;
import org.joda.time.DateTime;

import CT417_Assignment1.CourseProgram;
import CT417_Assignment1.Lecturer;
import CT417_Assignment1.Module;
import CT417_Assignment1.Student;


public class App {
    
    public static void main(String[] args) {

        // Lecturers
        Lecturer mG = new Lecturer("Michael Golden", 50, "11/12/1972");
        Lecturer dL = new Lecturer("David Lynch", 56, "09/12/1966");
        Lecturer lK = new Lecturer("Loreta Kenny", 35, "11/04/1989");
        Lecturer oH = new Lecturer("Oisin Hodgins", 28, "14/10/1994");

        //Lecturers array
        ArrayList<Lecturer> lecturersArray = new ArrayList<>();
        lecturersArray.add(oH);
        lecturersArray.add(mG);
        lecturersArray.add(dL);
        lecturersArray.add(lK);

        //Courses Name
        CourseProgram law = new CourseProgram("Law");
        CourseProgram commerce = new CourseProgram("Commerce");
        CourseProgram lawAndBusiness = new CourseProgram("Law and Business");

        //Courses start and end dates
        DateTime startDate = new DateTime(2019,9,1,9,0); 
        DateTime endDate = new DateTime(2023,5,31,9,0); 
        law.setStartDate(startDate);
        law.setEndDate(endDate);
        commerce.setStartDate(startDate);
        commerce.setEndDate(endDate);
        lawAndBusiness.setStartDate(startDate);
        lawAndBusiness.setEndDate(endDate);


        //Courses main array for iteration
        ArrayList<CourseProgram> coursesArray = new ArrayList<>();
        coursesArray.add(law);
        coursesArray.add(lawAndBusiness);
        coursesArray.add(commerce);

        //Courses Sub Arrays to be added to modules
        ArrayList<CourseProgram> lawArray = new ArrayList<>();
        lawArray.add(law);
        lawArray.add(lawAndBusiness);
        ArrayList<CourseProgram> commerceArray = new ArrayList<>();
        commerceArray.add(lawAndBusiness);
        commerceArray.add(commerce);


        //Modules create
        Module law101 = new Module("law101", "L101", oH, lawArray);
        Module constitutionalLaw = new Module("constitutionalLaw", "L235", dL, lawArray);
        Module tortLaw = new Module("tortLaw", "L354", dL, lawArray);


        Module business101 = new Module("business101", "B101", mG, commerceArray);
        Module econometrics = new Module("econometrics", "E140", lK, commerceArray);
        Module macroEconomics = new Module("macroEconomics", "E190", lK, commerceArray);


        //Full modules array    
        ArrayList<Module> modulesArray = new ArrayList<>();
        modulesArray.add(business101);
        modulesArray.add(econometrics);
        modulesArray.add(macroEconomics);
        modulesArray.add(law101);
        modulesArray.add(constitutionalLaw);
        modulesArray.add(tortLaw);

        ArrayList<Module> commerceModulesArray = new ArrayList<>();
        commerceModulesArray.add(business101);
        commerceModulesArray.add(econometrics);
        commerceModulesArray.add(macroEconomics);

        ArrayList<Module> lawModulesArray = new ArrayList<>();
        lawModulesArray.add(law101);
        lawModulesArray.add(constitutionalLaw);
        lawModulesArray.add(tortLaw);


        //Add modules to the appropriate courses use for loop through modules 
        law.addModules(lawModulesArray);
        commerce.addModules(commerceModulesArray);
        lawAndBusiness.addModules(lawModulesArray);
        lawAndBusiness.addModules(commerceModulesArray);
        
        
        //Add modules to lecturers do this with for loop through modules 
        for (Lecturer lecturer : lecturersArray){
            for(Module module : modulesArray){
                if(lecturer.equals(module.getLecturer())){
                    lecturer.addModule(module);
                }
            }
        }
        //Create student objects with details + course + course.getmodules

        Student mL = new Student("Michael Lowry", 19, "20/10/2000", lawAndBusiness, lawAndBusiness.getModules());
        Student dG = new Student("Dara Golden", 21, "20/10/2000", lawAndBusiness, lawAndBusiness.getModules());
        Student lG = new Student("Liam Golden", 22, "20/10/2000", commerce, commerce.getModules());
        Student mKG = new Student("Molly Kelly Grealy", 22, "20/10/2000", commerce, commerce.getModules());
        Student mB = new Student("Mark Boyle", 24, "20/10/2030", law, law.getModules());
        Student sG = new Student("Sam Golden", 20, "20/10/2000", law, law.getModules());
 

        //Create student array
        ArrayList<Student> studentsArray = new ArrayList<>();
        studentsArray.add(sG);
        studentsArray.add(mL);
        studentsArray.add(dG);
        studentsArray.add(lG);
        studentsArray.add(mKG);
        studentsArray.add(mB);
        studentsArray.add(sG);

        //add students to modules and courses by checking course and then
        for(Student student : studentsArray){
            student.getCourse().addStudent(student);
            for(Module module : student.getModules()){
                module.addStudent(student);
            }
        }

        System.out.println("Now printing a list of all available courses with their modules");
        for(CourseProgram course : coursesArray){

        System.out.println("\n" + course.getName() + ":");

        for(Module module : course.getModules()){
            System.out.print(module.getName() + " ");       
            }
        System.out.println();
    
        }

        System.out.println("Now printing a list of all Students usernames with their courses and modules");
        for(Student student : studentsArray){
            System.out.println("\n \n" + student.getUsername() + ":");
            
            System.out.print("Course: " + student.getCourse().getName() + " Modules: ");
            for(Module module : student.getModules()){
                System.out.print(module.getName() + " ");       
            }
        }
       




    }
}
